/**
 * ONE-TIME script to restore the Dragonite team data for share TRjVuD8B.
 * Run after deploying: npx tsx scripts/restore-dragonite.ts
 * Then delete this file and the /api/restore route.
 */

const RESTORE_URL = "https://vgc-team-report.vercel.app/api/restore";

const data = {
  calcs: {
    Entei: [
      { text: "252+ Atk Mystic Water Urshifu-Rapid Strike Surging Strikes (3 hits) vs. 68 HP  / 4 Def Tera-Normal Entei on a critical hit: 147-174 (73.8 - 87.4%) -- guaranteed 2HKO", category: "defensive" },
      { text: "252 SpA Life Orb Sheer Force Landorus Earth Power vs. 68 HP  / 44 SpD Tera-Normal Entei: 142-169 (71.3 - 84.9%) -- guaranteed 2HKO", category: "defensive" },
      { text: "252+ Atk Life Orb Tera-Normal Entei Sacred Fire vs. 244 HP  / 156+ Def Amoonguss: 221-265 (100.4 - 120.4%) -- guaranteed OHKO", category: "offensive" },
      { text: "252+ Atk Life Orb Sword of Ruin Entei Stone Edge vs. 228 HP  / 188+ Def Incineroar: 164-195 (82.4 - 97.9%) -- guaranteed 2HKO", category: "offensive" },
      { text: "Outspeeds Flutter Mane after an Icy Wind", category: "speed" },
    ],
    "Chien-Pao": [
      { text: "252+ Atk Urshifu-Rapid Strike Surging Strikes (3 hits) vs. 0 HP  / 4 Def Chien-Pao on a critical hit: 126-153 (81.2 - 98.7%) -- guaranteed 2HKO", category: "defensive" },
      { text: "252+ Atk Sword of Ruin Chien-Pao Ice Spinner vs. 84 HP  / 20 Def Raging Bolt: 204-240 (96.6 - 113.7%) -- 75% chance to OHKO", category: "offensive" },
      { text: "252+ Atk Sword of Ruin Chien-Pao Ice Spinner vs. 244 HP  / 156+ Def Amoonguss: 188-224 (85.4 - 101.8%) -- 12.5% chance to OHKO", category: "offensive" },
    ],
    Dragonite: [
      { text: "252+ SpA Dragon Fang Dragon's Maw Regidrago Dragon Energy (150 BP) vs. 84 HP  / 28 SpD Tera-Normal Dragonite: 153-181 (86.4 - 102.2%) -- 18.75% chance to OHKO", category: "defensive" },
      { text: "36 SpA Flutter Mane Moonblast vs. 84 HP  / 28 SpD Dragonite: 138-164 (77.9 - 92.6%) -- guaranteed 2HKO", category: "defensive" },
      { text: "252+ Atk Choice Band Sword of Ruin Tera-Normal Dragonite Extreme Speed vs. 60 HP  / 4 Def Urshifu-Rapid Strike: 153-180 (83.6 - 98.3%) -- guaranteed 2HKO", category: "offensive" },
      { text: "156+ Atk Sword of Ruin Urshifu-Rapid Strike Surging Strikes (3 hits) vs. 84 HP  / 4 Def Tera-Normal Dragonite on a critical hit: 138-165 (77.9 - 93.2%) -- guaranteed 2HKO", category: "defensive" },
      { text: "252+ Atk Choice Band Sword of Ruin Tera-Normal Dragonite Extreme Speed vs. 252 HP  / 4 Def Rillaboom: 166-196 (80.1 - 94.6%) -- guaranteed 2HKO after Grassy Terrain recovery", category: "offensive" },
      { text: "252+ Atk Choice Band Dragonite Aqua Jet vs. 236 HP  / 252+ Def Flutter Mane: 40-48 (25 - 30%) -- guaranteed 4HKO", category: "offensive" },
      { text: "252+ Atk Choice Band Dragonite Aqua Jet vs. 116 HP  / 12 Def Landorus: 84-100 (46.9 - 55.8%) -- 76.17% chance to 2HKO", category: "offensive" },
      { text: "252+ Atk Choice Band Dragonite Aqua Jet vs. 4 HP  / 0 Def Arcanine-Hisui: 184-220 (107.6 - 128.6%) -- guaranteed OHKO", category: "offensive" },
    ],
    "Raging Bolt": [
      { text: "252+ Atk Sword of Ruin Chien-Pao Ice Spinner vs. 108 HP  / 124 Def Raging Bolt: 182-216 (85 - 100.9%) -- 6.25% chance to OHKO", category: "defensive" },
      { text: "252+ Atk Sword of Ruin Chien-Pao Icicle Crash vs. 108 HP  / 124 Def Raging Bolt: 192-228 (89.7 - 106.5%) -- 37.5% chance to OHKO", category: "defensive" },
      { text: "252+ Atk Guts Ursaluna Facade (140 BP) vs. 108 HP  / 124 Def Raging Bolt: 196-232 (91.5 - 108.4%) -- 50% chance to OHKO", category: "defensive" },
      { text: "Outspeed Special Attack Booster Iron Crown After 1 Icy Wind", category: "speed" },
      { text: "100+ SpA Raging Bolt Snarl vs. 0 HP  / 4 SpD Iron Crown: 46-56 (27.8 - 33.9%) -- 0.24% chance to 3HKO", category: "offensive" },
      { text: "100+ SpA Raging Bolt Electroweb vs. 60 HP  / 124 SpD Urshifu-Rapid Strike: 92-110 (50.2 - 60.1%) -- guaranteed 2HKO", category: "offensive" },
      { text: "164+ SpA Archaludon Draco Meteor vs. 108 HP  / 36 SpD Assault Vest Raging Bolt: 156-186 (72.8 - 86.9%) -- guaranteed 2HKO", category: "defensive" },
    ],
    "Flutter Mane": [
      { text: "Faster Than Regidrago after TW", category: "speed" },
      { text: "252+ Atk Sword of Ruin Chien-Pao Ice Spinner vs. 148 HP  / 148 Def Flutter Mane: 123-145 (82.5 - 97.3%) -- guaranteed 2HKO", category: "defensive" },
      { text: "156+ Atk Urshifu-Rapid Strike Surging Strikes (3 hits) vs. 148 HP  / 148 Def Flutter Mane on a critical hit: 126-153 (84.5 - 102.6%) -- 0.68% chance to OHKO", category: "defensive" },
      { text: "252+ Atk Guts Ursaluna Headlong Rush vs. 148 HP  / 148 Def Tera-Grass Flutter Mane: 114-134 (76.5 - 89.9%) -- guaranteed 2HKO", category: "defensive" },
      { text: "-1 252 SpA Quark Drive Iron Crown Tachyon Cutter (2 hits) vs. 148 HP  / 4 SpD Flutter Mane: 112-136 (75.1 - 91.2%) -- guaranteed 2HKO", category: "defensive" },
      { text: "76 Atk Ogerpon-Hearthflame Wood Hammer (1.2x Mask Boost) vs. 148 HP  / 148 Def Flutter Mane: 130-154 (87.2 - 103.3%) -- 18.75% chance to OHKO", category: "defensive" },
      { text: "36 SpA Flutter Mane Moonblast vs. 60 HP  / 124 SpD Urshifu-Rapid Strike: 180-212 (98.3 - 115.8%) -- 81.25% chance to OHKO", category: "offensive" },
      { text: "76+ Atk Incineroar Flare Blitz vs. 148 HP  / 148 Def Flutter Mane: 115-136 (77.1 - 91.2%) -- guaranteed 2HKO", category: "defensive" },
      { text: "100 Atk Gouging Fire Heat Crash (120 BP) vs. 148 HP  / 148 Def Flutter Mane: 108-127 (72.4 - 85.2%) -- guaranteed 2HKO", category: "defensive" },
      { text: "Faster than Max Speed Dozo", category: "speed" },
    ],
    "Urshifu-Rapid-Strike": [
      { text: "Faster than Adamant Chien-Pao after Icy Wind", category: "speed" },
      { text: "108+ SpA Raging Bolt Thunderclap vs. 68 HP  / 124 SpD Urshifu-Rapid Strike: 156-186 (84.7 - 101%) -- 6.25% chance to OHKO", category: "defensive" },
      { text: "244+ Atk Mystic Water Urshifu-Rapid Strike Surging Strikes (3 hits) vs. 0 HP  / 4 Def Chien-Pao on a critical hit: 156-189 (100.6 - 121.9%) -- guaranteed OHKO", category: "offensive" },
      { text: "244+ Atk Mystic Water Sword of Ruin Urshifu-Rapid Strike Surging Strikes (3 hits) vs. 188 HP  / 52 Def Ogerpon-Hearthflame on a critical hit: 183-219 (102.2 - 122.3%) -- guaranteed OHKO", category: "offensive" },
    ],
  },
  notes: {
    Entei: "Entei\u2019s primary function was crippling opposing offensive Pok\u00e9mon through Sacred Fire\u2019s 50% burn chance, disrupting physical attackers throughout the game. Extreme Speed provided priority cleanup potential, especially under Tera Normal with Chien-Pao\u2019s support boosting its damage. Stone Edge targeted Tornadus for super-effective damage and was also a strong option into Incineroar. Overall, Entei\u2019s value lay in its ability to weaken opposing Pok\u00e9mon with burns while threatening KOs with Life Orb-boosted Tera Normal Extreme Speed.",
    "Chien-Pao": "Chien-Pao\u2019s primary role was to support the priority attackers on the team while also serving as a Terrain removal option. Terrain from psy-spam teams was a significant issue, as it shut down priority moves entirely so Ice Spinner was critical for this. Sucker Punch provided a reliable way to punish Tera Ghost Ursaluna and Tera Ghost Incineroar and Flutter Mane, both of which came up frequently throughout the event \u2014 particularly given the team\u2019s heavy reliance on Extreme Speed.",
    Dragonite: "Dragonite\u2019s main role was as a cleanup attacker, using Tera Normal Extreme Speed to close out endgames \u2014 particularly alongside Chien-Pao\u2019s Sword of Ruin support. In positions where Icy Wind or Electroweb had already been applied and Dragonite was definitively faster, Outrage became a powerful option for raw damage. Aqua Jet was another key tool, especially with Landorus-based teams running Flutter Mane being common in the metagame. In situations where Extreme Speed was blocked, having a secondary priority move that still dealt meaningful damage with Choice Band \u2014 especially next to Chien-Pao was invaluable. Doubling up on Aqua Jet alongside Urshifu-Rapid-Strike was also a strong line for cleaning up endgames. The 118 Speed stat ensured Dragonite would outspeed anything below 176 Speed after an Icy Wind. In hindsight, investing slightly more into Speed to outpace Ogerpon would have been a worthwhile adjustment, as that proved to be a minor issue during the event. That said, the bulk on this set was excellent and allowed Dragonite to tank hits reliably throughout the tournament.",
    "Raging Bolt": "Raging Bolt served as the team\u2019s damage mitigation and speed control option, proving especially valuable in Psyspam matchups. After an Icy Wind from Flutter Mane, Raging Bolt would outspeed boosted Iron Crown and apply Snarl to reduce its Special Attack, allowing Flutter Mane to survive Tachyon Cutter. Electroweb provided an alternative form of speed control in games where Flutter Mane wasn\u2019t leading, given how much frailer it is. Defensively, Raging Bolt had the bulk to survive Ice Spinner in most scenarios while maintaining solid sustain. The Speed investment was deliberate \u2014 it needed to outspeed anything at base 168 Speed or lower after an Icy Wind, ensuring it could act before key threats in those positions.",
    "Flutter Mane": "Flutter Mane was the centrepiece of the team. While not necessarily the MVP in terms of raw output, the role it fulfilled was indispensable \u2014 speed control, disruption, and enabling the rest of the team all in one. Icy Wind was the primary form of speed control, and most of the Speed benchmarks across the team are built around outspeeding key threats after a single Icy Wind. Thunder Wave provided a secondary layer of disruption, helping the offensive Pok\u00e9mon distribute as much damage as possible. Tera Grass was pivotal, allowing Flutter Mane to ignore Rage Powder and freely Thunder Wave specific slots or Taunt Porygon-2 \u2014 particularly useful against Amoonguss and Porygon-2 leads. Moonblast rounded out the set as a strong offensive Fairy-type option. The spread was built to be bulky while remaining faster than Regidrago.",
    "Urshifu-Rapid-Strike": "Urshifu brought relentless offensive pressure, especially in combination with Flutter Mane\u2019s Icy Wind and Thunder Wave support. With speed control established, Urshifu could enter the game confidently, knowing it would outspeed Ogerpon and simply click Surging Strikes. Without redirection on the opposing side, very few Pok\u00e9mon could absorb the hits \u2014 particularly at 244 Attack Adamant. Next to Chien-Pao, the damage output became even more punishing. For example, against Amoonguss on the field, even if the opponent Tera\u2019d to resist Ice Spinner, Surging Strikes would comfortably remove it \u2014 especially through Tera Fairy. Tera Steel was also critical for Urshifu, reducing the damage taken from Bleakwind Storm, Fairy-type moves and into Psyspam too. The bulk investment was intentional, with just enough Speed to outpace anything slower than Adamant Chien-Pao after an Icy Wind, while maximising damage output otherwise.",
  },
  paste: "Chien-Pao @ Focus Sash  \r\nAbility: Sword of Ruin  \r\nShiny: Yes  \r\nTera Type: Ghost  \r\nEVs: 252 Atk / 4 Def / 252 Spe  \r\nAdamant Nature  \r\nIVs: 20 SpA  \r\n- Sacred Sword  \r\n- Ice Spinner  \r\n- Sucker Punch  \r\n- Protect  \r\n\r\nRaging Bolt @ Assault Vest  \r\nAbility: Protosynthesis  \r\nTera Type: Fairy  \r\nEVs: 108 HP / 124 Def / 100 SpA / 36 SpD / 140 Spe  \r\nModest Nature  \r\nIVs: 20 Atk  \r\n- Thunderclap  \r\n- Draco Meteor  \r\n- Electroweb  \r\n- Snarl  \r\n\r\nDragonite @ Choice Band  \r\nAbility: Inner Focus  \r\nTera Type: Normal  \r\nEVs: 84 HP / 252 Atk / 4 Def / 28 SpD / 140 Spe  \r\nAdamant Nature  \r\n- Outrage  \r\n- Extreme Speed  \r\n- Stomping Tantrum  \r\n- Aqua Jet  \r\n\r\nFlutter Mane @ Booster Energy  \r\nAbility: Protosynthesis  \r\nTera Type: Grass  \r\nEVs: 148 HP / 148 Def / 36 SpA / 4 SpD / 172 Spe  \r\nTimid Nature  \r\nIVs: 17 Atk  \r\n- Moonblast  \r\n- Icy Wind  \r\n- Taunt  \r\n- Thunder Wave  \r\n\r\nEntei @ Life Orb  \r\nAbility: Inner Focus  \r\nLevel: 50  \r\nTera Type: Normal  \r\nEVs: 68 HP / 252 Atk / 4 Def / 44 SpD / 140 Spe  \r\nAdamant Nature  \r\n- Sacred Fire  \r\n- Extreme Speed  \r\n- Stone Edge  \r\n- Protect  \r\n\r\nUrshifu-Rapid-Strike @ Mystic Water  \r\nAbility: Unseen Fist  \r\nTera Type: Steel  \r\nEVs: 68 HP / 244 Atk / 4 Def / 124 SpD / 68 Spe  \r\nAdamant Nature  \r\n- Surging Strikes  \r\n- Aqua Jet  \r\n- Close Combat  \r\n- Detect  \r\n\r\n",
  roles: {
    Entei: "Priority Clean Up v2",
    "Chien-Pao": "Offensive Support",
    Dragonite: "Priority Clean Up ",
    "Raging Bolt": "Damage Mitigation and Speed Control ",
    "Flutter Mane": "Speed Control ",
    "Urshifu-Rapid-Strike": "",
  },
  record: "10-3",
  mvpIndex: 2,
  placement: "18th",
  rentalCode: "C5W8G4",
  teamSummary: "This is a priority-heavy team built around overwhelming the opponent before they get a chance to act. The core strategy is simple \u2014 by spamming priority moves, the team aims to strike first and pin down key targets before they can respond. If the opponent can\u2019t move first, they can\u2019t output damage, and with the sheer offensive power behind these priority attacks, their Pok\u00e9mon won\u2019t be staying on the field for long either. The team is designed to control the pace of the game from turn one and never give it back.",
  hiddenSlides: ["matchup-sheet"],
  matchupPlans: [
    {
      gamePlans: [{ bring: [4, 3, 2, 0], notes: "Lead: Entei + Flutter Mane\nThe core reason for leading Entei and Flutter Mane together is that Entei, as an Inner Focus Pok\u00e9mon, cannot be Faked Out \u2014 allowing both Pok\u00e9mon to act freely on turn one. Against Tera Urshifu with Choice Scarf, the combination of Moonblast plus Tera Normal Extreme Speed had a very high likelihood of securing the KO, making this a reliable lead into those compositions.\nBeyond that, if Urshifu wasn\u2019t a concern on the opposing side, this lead opened up strong offensive lines. Icy Wind into Landorus followed by Sacred Fire dealt significant damage \u2014 and if Landorus was Tera Steel, it could outright KO it. Against Incineroar and Rillaboom, the options were equally strong: doubling into one slot with Moonblast and Stone Edge, or splitting damage with Moonblast into Incineroar and Sacred Fire into Rillaboom. These plays were especially effective given that Assault Vest Rillaboom and Safety Goggles Incineroar both lack Protect, leaving them vulnerable to repeated offensive pressure.\n\nEndgame: Dragonite + Chien-Pao\nIf the opponent has been forced to Tera earlier in the game, there are no Tera Ghost options remaining. At that point, Dragonite and Chien-Pao can close things out cleanly \u2014 spamming Extreme Speed and Sucker Punch to pick off the remaining Pok\u00e9mon with priority." }],
      opponentLabel: "VGC CORNER OFFICIAL BALANCE PASTE",
      opponentPaste: "Urshifu-Rapid-Strike @ Choice Scarf  \r\nAbility: Unseen Fist  \r\nLevel: 50  \r\nTera Type: Steel  \r\nEVs: 12 HP / 156 Atk / 4 Def / 156 SpD / 180 Spe  \r\nAdamant Nature  \r\n- Surging Strikes  \r\n- Close Combat  \r\n- Aqua Jet  \r\n- U-turn  \r\n\r\nChien-Pao @ Focus Sash  \r\nAbility: Sword of Ruin  \r\nLevel: 50  \r\nTera Type: Ghost  \r\nEVs: 252 Atk / 4 Def / 252 Spe  \r\nAdamant Nature  \r\nIVs: 19 SpA  \r\n- Protect  \r\n- Icicle Crash  \r\n- Sucker Punch  \r\n- Sacred Sword  \r\n\r\nRaging Bolt @ Leftovers  \r\nAbility: Protosynthesis  \r\nLevel: 50  \r\nTera Type: Fairy  \r\nEVs: 188 HP / 140 Def / 108 SpA / 4 SpD / 68 Spe  \r\nModest Nature  \r\nIVs: 20 Atk  \r\n- Thunderclap  \r\n- Dragon Pulse  \r\n- Calm Mind  \r\n- Protect  \r\n\r\nLandorus @ Life Orb  \r\nAbility: Sheer Force  \r\nLevel: 50  \r\nTera Type: Poison  \r\nEVs: 132 HP / 4 Def / 116 SpA / 4 SpD / 252 Spe  \r\nModest Nature  \r\nIVs: 0 Atk  \r\n- Earth Power  \r\n- Sludge Bomb  \r\n- Substitute  \r\n- Protect  \r\n\r\nIncineroar @ Safety Goggles  \r\nAbility: Intimidate  \r\nLevel: 50  \r\nTera Type: Ghost  \r\nEVs: 252 HP / 204 Def / 52 SpD  \r\nImpish Nature  \r\nIVs: 22 SpA / 20 Spe  \r\n- Parting Shot  \r\n- Flare Blitz  \r\n- Will-O-Wisp  \r\n- Fake Out  \r\n\r\nRillaboom @ Assault Vest  \r\nAbility: Grassy Surge  \r\nLevel: 50  \r\nTera Type: Fire  \r\nEVs: 252 HP / 116 Atk / 4 Def / 124 SpD / 12 Spe  \r\nAdamant Nature  \r\nIVs: 0 SpA  \r\n- Wood Hammer  \r\n- Grassy Glide  \r\n- U-turn  \r\n- Fake Out",
    },
    {
      gamePlans: [
        { bring: [3, 4, 0, 2], notes: "Lead: Flutter Mane + Entei\n\nThis matchup followed a similar lead to the previous one \u2014 Flutter Mane and Entei. Tera Grass on Flutter Mane was key here, as it allowed Flutter Mane to Taunt Porygon-2 without being redirected by Rage Powder from Amoonguss. Alternatively, you could Taunt the Amoonguss directly and click Sacred Fire with Entei.\n\nIn some games, the stronger line was actually to Stone Edge rather than Sacred Fire. The reasoning was that you didn\u2019t necessarily want to KO Amoonguss too early \u2014 with Tera Grass preventing Spore, Amoonguss was effectively neutralised on the field. If Trick Room went up and Amoonguss had already gone down, Ursaluna would have a free switch-in with nothing blocking it. Keeping Amoonguss alive while pressuring with Stone Edge was a deliberate choice, and one I used in a few games including Round Three.\n\nBack: Dragonite + Chien-Pao\n\nDragonite and Chien-Pao sat in the back to clean up. Against this composition, if the opponent hadn\u2019t Tera\u2019d \u2014 or had used their Tera early on Amoonguss \u2014 there was no way to block the Extreme Speed and Sucker Punch combination in the endgame. If neither Ursaluna nor Incineroar could Tera Ghost, priority had free rein. The opponent typically didn\u2019t bring Flutter Mane into this matchup either, which made these four Pok\u00e9mon the ideal selection." },
        { bring: [3, 4, 0, 5], notes: "In some games, bringing Urshifu in the back instead of Dragonite was the stronger play. If Flutter Mane wasn\u2019t coming from the opponent\u2019s side and Tera had been forced onto Amoonguss, the remaining Pok\u00e9mon were typically Ursaluna and Incineroar. With Urshifu next to Chien-Pao, you could simply click Surging Strikes and remove whichever Pok\u00e9mon was in the other slot.\nAgainst a priority-heavy team with no redirection available, the opponent\u2019s only options were to Protect repeatedly or constantly switch. This is exactly where Surging Strikes thrived \u2014 as a multi-hit move that bypasses Protect and crits every time, it punished both switches and Pok\u00e9mon staying in. With 244 Attack Adamant and Mystic Water boosting its damage, backed by Chien-Pao\u2019s Sword of Ruin, Surging Strikes brought everything so low that even if a Pok\u00e9mon switched in to absorb the first hit, a second Surging Strikes would finish the job." },
      ],
      opponentLabel: "Nils Dunlop\u2019s 2024 Europe Internationals Open Team List",
      opponentPaste: "Urshifu-Rapid-Strike @ Choice Scarf  \r\nAbility: Unseen Fist  \r\nLevel: 50  \r\nTera Type: Water  \r\nEVs: 60 HP / 156 Atk / 4 Def / 124 SpD / 164 Spe  \r\nAdamant Nature  \r\n- Close Combat  \r\n- Surging Strikes  \r\n- Aqua Jet  \r\n- U-turn  \r\n\r\nPorygon2 @ Eviolite  \r\nAbility: Download  \r\nLevel: 50  \r\nTera Type: Flying  \r\nEVs: 252 HP / 4 Atk / 124 Def / 92 SpA / 36 SpD  \r\nQuiet Nature  \r\nIVs: 0 Spe  \r\n- Tera Blast  \r\n- Ice Beam  \r\n- Recover  \r\n- Trick Room  \r\n\r\nUrsaluna @ Flame Orb  \r\nAbility: Guts  \r\nLevel: 50  \r\nTera Type: Ghost  \r\nEVs: 140 HP / 252 Atk / 116 SpD  \r\nBrave Nature  \r\nIVs: 0 Spe  \r\n- Facade  \r\n- Headlong Rush  \r\n- Earthquake  \r\n- Protect  \r\n\r\nAmoonguss @ Rocky Helmet  \r\nAbility: Regenerator  \r\nLevel: 50  \r\nTera Type: Ghost  \r\nEVs: 236 HP / 236 Def / 36 SpD  \r\nBold Nature  \r\nIVs: 0 Atk / 27 Spe  \r\n- Spore  \r\n- Rage Powder  \r\n- Sludge Bomb  \r\n- Protect  \r\n\r\nIncineroar @ Sitrus Berry  \r\nAbility: Intimidate  \r\nLevel: 50  \r\nTera Type: Grass  \r\nEVs: 252 HP / 36 Atk / 4 Def / 4 SpD / 212 Spe  \r\nAdamant Nature  \r\n- Fake Out  \r\n- Flare Blitz  \r\n- Knock Off  \r\n- Parting Shot  \r\n\r\nFlutter Mane @ Booster Energy  \r\nAbility: Protosynthesis  \r\nLevel: 50  \r\nTera Type: Fairy  \r\nEVs: 212 HP / 132 Def / 44 SpA / 4 SpD / 116 Spe  \r\nModest Nature  \r\nIVs: 0 Atk  \r\n- Moonblast  \r\n- Shadow Ball  \r\n- Substitute  \r\n- Protect",
    },
    {
      gamePlans: [
        { bring: [3, 4, 0, 2], notes: "The reason for leading Entei into these compositions was its ability to sacrifice value while applying burns. Sacred Fire into either Ting-Lu or Dondozo created long-term pressure, and since Dondozo has Oblivious, it can\u2019t be Taunted. Burning the Pok\u00e9mon was my primary way of limiting the damage from the other side. Against Ting-Lu, Taunt was available if needed, and using Tera Normal on Entei allowed it to trade more efficiently into Dondozo while staying on the field longer.\nThunder Wave also played a significant role in this matchup. When the opponent led Gouging Fire alongside their core, Flutter Mane could Thunder Wave it immediately, and Entei could follow up with Stone Edge to remove it before Breaking Swipe reduced Entei\u2019s Attack. Entei\u2019s coverage across this archetype was excellent \u2014 it threatened Gholdengo, burned Dragonite and Chien-Pao with Sacred Fire, hit Chien-Pao super effectively, and applied burns to Ting-Lu to weaken it over time.\n\nEndgame: Chien-Pao + Dragonite\n\nWith Moonblast pressuring Ting-Lu from Flutter Mane throughout the game, and the opponent likely having used their Tera early, the endgame followed the same priority cleanup plan. Chien-Pao and Dragonite came in to close things out with Extreme Speed and Sucker Punch, picking off whatever remained." },
        { bring: [3, 4, 5, 0], notes: "\nAlternative Back: Urshifu-Rapid-Strike + Chien-Pao\n\nSimilar to the Porygon-2 / Ursaluna matchup, there was a case for adjusting the back line in Game Two by bringing Urshifu instead of Dragonite to push the advantage further.\nTera Steel on Urshifu was key here. Scale Shot from Dragonite didn\u2019t deal significant damage into it, and Gholdengo couldn\u2019t threaten it meaningfully either \u2014 especially with Chien-Pao able to Sucker Punch Gholdengo on the same turn. With Icy Wind reducing Gouging Fire\u2019s Speed, Urshifu could come in comfortably and click Surging Strikes freely. If the opposing Dragonite had used Scale Shot and dropped its own Defence, Surging Strikes punished it heavily at minus one. Across the board, Surging Strikes hit everything on the opposing side hard, making Urshifu a natural fit to apply pressure and close out games in this matchup." },
      ],
      opponentLabel: "Balan Tour Top 4",
      opponentPaste: "Ting-Lu @ Rocky Helmet  \r\nAbility: Vessel of Ruin  \r\nLevel: 50  \r\nTera Type: Poison  \r\nEVs: 212 HP / 4 Atk / 36 Def / 252 SpD / 4 Spe  \r\nImpish Nature  \r\n- Sand Tomb  \r\n- Body Press  \r\n- Ruination  \r\n- Protect  \r\n\r\nDondozo @ Leftovers  \r\nAbility: Oblivious  \r\nLevel: 50  \r\nTera Type: Grass  \r\nEVs: 244 HP / 4 Atk / 36 Def / 220 SpD / 4 Spe  \r\nImpish Nature  \r\n- Wave Crash  \r\n- Heavy Slam  \r\n- Yawn  \r\n- Protect  \r\n\r\nChien-Pao @ Focus Sash  \r\nAbility: Sword of Ruin  \r\nLevel: 50  \r\nTera Type: Stellar  \r\nEVs: 252 Atk / 4 Def / 252 Spe  \r\nAdamant Nature  \r\n- Icicle Crash  \r\n- Sucker Punch  \r\n- Sacred Sword  \r\n- Protect  \r\n\r\nDragonite @ Loaded Dice  \r\nAbility: Inner Focus  \r\nLevel: 50  \r\nTera Type: Steel  \r\nEVs: 84 HP / 212 Atk / 4 Def / 4 SpD / 204 Spe  \r\nAdamant Nature  \r\n- Scale Shot  \r\n- Iron Head  \r\n- Extreme Speed  \r\n- Protect  \r\n\r\nGouging Fire @ Booster Energy  \r\nAbility: Protosynthesis  \r\nLevel: 50  \r\nTera Type: Fairy  \r\nEVs: 148 HP / 100 Atk / 4 Def / 4 SpD / 252 Spe  \r\nJolly Nature  \r\n- Heat Crash  \r\n- Breaking Swipe  \r\n- Howl  \r\n- Protect  \r\n\r\nGholdengo @ Choice Specs  \r\nAbility: Good as Gold  \r\nLevel: 50  \r\nTera Type: Fairy  \r\nEVs: 228 HP / 76 Def / 132 SpA / 52 SpD / 20 Spe  \r\nModest Nature  \r\n- Make It Rain  \r\n- Shadow Ball  \r\n- Dazzling Gleam  \r\n- Trick",
    },
    {
      gamePlans: [
        { bring: [1, 3, 0, 2], notes: "Lead: Raging Bolt + Flutter Mane\n\nThis matchup was where the Icy Wind plus Snarl combination truly shone. Against the Special Attack-boosting Iron Crown, Flutter Mane\u2019s Icy Wind brought it below Raging Bolt\u2019s Speed tier, allowing Raging Bolt to act first and apply Snarl. Reducing Iron Crown\u2019s Special Attack meant Flutter Mane could survive Tachyon Cutter, while Expanding Force also dealt significantly less damage across the board. Indeedee typically carried Follow Me to redirect Taunt or Thunder Wave, but pressing Snarl into that slot was still highly effective.\nThe general game plan was to sit on the field as long as possible, spamming Snarl alongside Flutter Mane\u2019s Thunder Wave or Icy Wind to keep Raging Bolt faster than the opposing threats. By doing this, Psychic Terrain turns would naturally run out, opening the door for priority in the endgame.\n\nEndgame: Chien-Pao + Dragonite\n\nChien-Pao and Dragonite came in to clean up once Terrain had expired. In some games, preserving Tera for Dragonite was the correct play \u2014 particularly against Regidrago, where Tera allowed Dragonite to drop its Dragon-type weakness and survive Dragon Energy. From there, the priority combination of Extreme Speed and Sucker Punch closed things out." },
        { bring: [1, 3, 0, 5], notes: "Alternative Back: Urshifu-Rapid-Strike\n\nIn some games, I adjusted the back line to include Urshifu, particularly when I identified Regidrago, Tornadus, and Chien-Pao on the opposing team \u2014 all of which Urshifu matched up well against. Tera Steel was the key adjustment, allowing Urshifu to wall Regidrago\u2019s Dragon Energy entirely while also shrugging off Bleakwind Storm from Tornadus. Without the super-effective weakness and with Urshifu\u2019s natural bulk, it could stay on the field comfortably.\nOffensively, the 244 Attack Adamant spread meant Surging Strikes hit extremely hard, either chunking or outright KOing threats that had already been chipped by Icy Wind. If Ogerpon wasn\u2019t brought or had been slowed down, Urshifu had even more freedom to operate.\nThese were minor adjustments rather than wholesale changes to the game plan. When the primary lead and back line were working, I didn\u2019t deviate \u2014 but having the flexibility to swap in Urshifu when needed gave the team an extra layer of adaptability." },
      ],
      opponentLabel: "Justin Carris\u2019s 2024 Orlando Regionals Open Team List",
      opponentPaste: "Iron Crown @ Booster Energy  \r\nAbility: Quark Drive  \r\nLevel: 50  \r\nTera Type: Water  \r\nEVs: 4 HP / 252 SpA / 252 Spe  \r\nModest Nature  \r\n- Expanding Force  \r\n- Tachyon Cutter  \r\n- Tera Blast  \r\n- Protect  \r\n\r\nUrshifu-Rapid-Strike @ Choice Scarf  \r\nAbility: Unseen Fist  \r\nLevel: 50  \r\nTera Type: Water  \r\nEVs: 60 HP / 156 Atk / 4 Def / 124 SpD / 164 Spe  \r\nAdamant Nature  \r\n- Close Combat  \r\n- Surging Strikes  \r\n- Ice Spinner  \r\n- U-turn  \r\n\r\nOgerpon-Hearthflame @ Hearthflame Mask  \r\nAbility: Mold Breaker  \r\nLevel: 50  \r\nTera Type: Fire  \r\nEVs: 188 HP / 76 Atk / 52 Def / 4 SpD / 188 Spe  \r\nAdamant Nature  \r\n- Ivy Cudgel  \r\n- Wood Hammer  \r\n- Follow Me  \r\n- Spiky Shield  \r\n\r\nIndeedee-F @ Safety Goggles  \r\nAbility: Psychic Surge  \r\nLevel: 50  \r\nTera Type: Fairy  \r\nEVs: 252 HP / 252 Def / 4 SpD  \r\nBold Nature  \r\nIVs: 0 Atk  \r\n- Follow Me  \r\n- Helping Hand  \r\n- Trick Room  \r\n- Dazzling Gleam  \r\n\r\nRegidrago @ Dragon Fang  \r\nAbility: Dragon\u2019s Maw  \r\nLevel: 50  \r\nTera Type: Steel  \r\nEVs: 4 HP / 252 SpA / 252 Spe  \r\nTimid Nature  \r\n- Dragon Energy  \r\n- Draco Meteor  \r\n- Earth Power  \r\n- Protect  \r\n\r\nTornadus @ Focus Sash  \r\nAbility: Prankster  \r\nLevel: 77  \r\nTera Type: Steel  \r\nEVs: 36 HP / 12 Def / 204 SpA / 4 SpD / 252 Spe  \r\nTimid Nature  \r\nIVs: 0 Atk  \r\n- Protect  \r\n- Bleakwind Storm  \r\n- Tailwind  \r\n- Rain Dance",
    },
  ],
  tournamentName: "EUIC 14th February 2026",
};

async function restore() {
  const res = await fetch(RESTORE_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      secret: "restore-dragonite-2026",
      id: "TRjVuD8B",
      data,
    }),
  });
  const result = await res.json();
  console.log("Restore result:", result);
}

restore();
